bit_posts/urls.py
from django.urls import path
from .views import post_views 


app_name = 'bit_posts'

urlpatterns = [
    path('', post_views.PostListView.as_view(), name='post-list-create'),
    path('api/posts/', post_views.PostCreateAPIView.as_view(), name='api-post-create'),  
    path('post/<int:post_id>/create-comment/', post_views.create_comment, name='create-comment'),
    path('delete-comment/<int:comment_id>/', post_views.delete_comment, name='delete-comment'),
    path('edit-comment/<int:pk>/edit/', post_views.UpdateComment.as_view(), name='edit-comment'),  
    path('api/post/<int:post_id>/upvote/', post_views.upvote_post, name='upvote-post'),
    path('post-update/<int:pk>/', post_views.UpdatePost.as_view(), name='update-post'),
    path('post-delete/<int:pk>/', post_views.DeletePost.as_view(), name='delete-post'),
    path('post/<int:parent_comment_id>/reply/', post_views.create_subcomment, name='reply-comment'),
    path('subcomment/<int:subcomment_id>/delete/', post_views.delete_subcomment, name='delete-subcomment'),
    path('subcomment/<int:pk>/update/', post_views.UpdateSubcomment.as_view(), name='update-subcomment'),
    path('api/get-post-by-id/', post_views.get_post_by_id, name='get-post-by-id'),
    path('retrieve/', post_views.retrieve_view, name='find-by-id'), 
]




bit_users/urls.py
# appname/urls.py
from django.urls import path
from . import views

app_name = 'bit_users' 
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('home/', views.HomePageView.as_view(), name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

breddit_django/urls.py
from django.urls import include, path
from django.contrib import admin
from breddit_django import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from bit_posts.views import post_views 


urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('posts/', include('bit_posts.urls')),
    path('admin/', admin.site.urls), 
    path('users/', include('bit_users.urls')),
    path('contact/', views.ContactPage.as_view(), name='contact'),
    path('privacy/', views.PrivacyPage.as_view(), name='privacy'), 
    path('post/<int:post_id>/create-comment/', post_views.create_comment, name='create-comment'),
]


urlpatterns += staticfiles_urlpatterns()

templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us - Breddit</title>

    <link rel="stylesheet" type="text/css" href="{% static 'breddit/css/templates/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Breddit</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">

                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <!-- Display links for authenticated users -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bit_posts:post-list-create' %}">Create Post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bit_posts:find-by-id' %}">Find by ID</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bit_users:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <!-- Display links for non-authenticated users -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bit_posts:post-list-create' %}">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bit_users:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bit_users:signup' %}">Signup</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'privacy' %}">Privacy Policy</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link" href="https://www.instagram.com/breddit_canada/"><i class="fab fa-instagram"></i></a>
                        </li>
                    
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    
    
    <div class="container mt-5 mt-4 bg-light p-4" style="max-height: 300px; overflow-y: auto;">
        <h1 style="font-family: 'Helvetica Neue', sans-serif; font-size: 36px; font-weight: bold; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">Contact Us</h1>
        <p style="font-family: 'Arial', sans-serif; font-size: 18px; line-height: 1.5; text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);">
            Have questions, suggestions, or just want to chat about bread? We'd love to hear from you!
        </p>
    
        <!-- Contact Information -->
        <div class="mt-4">
            <p><strong>Contact Information:</strong></p>
            <p><strong>Phone:</strong> +1 226-501-5252 (9:00 AM - 5:00 PM EST)</p>
            <p><strong>Instagram:</strong> <a href="https://www.instagram.com/breddit_canada/" target="_blank">https://www.instagram.com/breddit_canada/</a></p>
        </div>
    </div>
    
    
    <footer class="bg-light d-sm-block fixed-bottom">
        <div class="container d-flex justify-content-center align-items-center">
            <ul class="list-inline mb-0">
                <li class="list-inline-item">
                    <a class="nav-link" href="https://www.instagram.com/breddit_canada/">
                        <i class="fab fa-instagram"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="nav-link" href="https://www.facebook.com/profile.php?id=61553991453763">
                        <i class="fab fa-facebook"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="nav-link" href="https://twitter.com/BredditCanada">
                        <i class="fab fa-twitter"></i>
                    </a>
                </li>
            </ul>
        </div>
    </footer>
 
    <script>
        // Initialize Bootstrap components
        $(document).ready(function () {
            // Initialize Bootstrap Navbar
            $('.navbar-toggler').click(function () {
                $('#navbarNav').toggleClass('show');
            });
        });
    </script>

</body>
</html>

   

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Breddit</title>

    <link rel="stylesheet" type="text/css" href="{% static 'breddit/css/templates/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>

<body>
    <nav id="div1" class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container" >
            <a class="navbar-brand" href="{% url 'home' %}">Breddit</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_posts:post-list-create' %}">Create Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_posts:find-by-id' %}">Find by ID</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_users:logout' %}">Logout</a>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_posts:post-list-create' %}">Posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_users:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_users:signup' %}">Signup</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'privacy' %}">Privacy Policy</a>
                    </li> 
                    <li class="nav-item">
                        <a class="nav-link" href="https://www.instagram.com/breddit_canada/"><i class="fab fa-instagram"></i></a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
  
    <div class="container mt-5 mt-4 bg-light p-4" style="max-height: 500px; overflow-y: auto;">
        <h1 style="font-family: 'Helvetica Neue', sans-serif; font-size: 36px; font-weight: bold; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">About Breddit</h1>
        <p style="font-family: 'Arial', sans-serif; font-size: 18px; line-height: 1.5; text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);">
            Welcome to Breddit, the ultimate community for bread enthusiasts! Breddit is a platform where you can share your love for bread, discover new bread recipes, and engage in discussions about your favorite carb-loaded creations.
        </p>
        <p style="font-family: 'Arial', sans-serif; font-size: 18px; line-height: 1.5; text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);">
            At Breddit, we believe that bread is more than just a staple food; it's an art form, a source of comfort, and a topic worth celebrating. We're here to provide a space for bread lovers to connect, learn, and share their passion.
        </p>

        </p>
        <p style="font-family: 'Arial', sans-serif; font-size: 18px; line-height: 1.5; text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);">
            Join us on this delicious journey, explore mouthwatering recipes, and debate the eternal question: "Is garlic bread the best bread?" We invite you to be a part of Breddit and spread the love of bread far and wide.
        </p>
        {% if not user.is_authenticated %}
        <p>
            <a href="{% url 'bit_users:signup' %}">
                <button style="font-family: 'Arial', sans-serif; font-size: 20px; padding: 10px 20px; background-color: #ff6600; color: white; border: none; cursor: pointer; text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.2);">Join Now</button>
            </a>
            <a href="{% url 'bit_users:login' %}">
                <button style="font-family: 'Arial', sans-serif; font-size: 20px; padding: 10px 20px; background-color: #007bff; color: white; border: none; cursor: pointer; text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.2);">Log In</button>
            </a>
        </p>
        {% endif %}
    </div>
        {% if messages %}
        <div class="alert alert-dismissible fade show alert-warning" role="alert">
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %} style="font-weight: bold";>{{ message }}</li>
                {% endfor %}
            </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
    <br>
    </div>
    
    <!-- footer-->
    <footer class="bg-light d-sm-block fixed-bottom">
        <div class="container d-flex justify-content-center align-items-center">
            <ul class="list-inline mb-0">
                <li class="list-inline-item">
                    <a class="nav-link" href="https://www.instagram.com/breddit_canada/">
                        <i class="fab fa-instagram"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="nav-link" href="https://www.facebook.com/profile.php?id=61553991453763">
                        <i class="fab fa-facebook"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="nav-link" href="https://twitter.com/BredditCanada">
                        <i class="fab fa-twitter"></i>
                    </a>
                </li>
            </ul>
        </div>
    </footer>
    

<script>
    // Initialize Bootstrap components
    $(document).ready(function () {
        // Initialize Bootstrap Navbar
        $('.navbar-toggler').click(function () {
            $('#navbarNav').toggleClass('show');
        });
    });
</script>
<script>
    // Initialize Bootstrap components
    $(document).ready(function () {
        // Initialize Bootstrap Carousel
        $('#about-carousel').carousel();
    });
</script>


</body>
</html>

templates/privacy.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us - Breddit</title>

    <link rel="stylesheet" type="text/css" href="{% static 'breddit/css/templates/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Breddit</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <!-- Display links for authenticated users -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bit_posts:post-list-create' %}">Create Post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bit_posts:find-by-id' %}">Find by ID</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bit_users:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <!-- Display links for non-authenticated users -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bit_posts:post-list-create' %}">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bit_users:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bit_users:signup' %}">Signup</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'privacy' %}">Privacy Policy</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link" href="https://www.instagram.com/breddit_canada/"><i class="fab fa-instagram"></i></a>
                        </li>
                    
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    
    
    <div class="container mt-5 mt-4 bg-light p-4"style="max-height: 300px; overflow-y: auto;">
        <h1 style="font-family: 'Helvetica Neue', sans-serif; font-size: 36px; font-weight: bold; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">Privacy Policy</h1>
    

    
        <!-- Privacy Policy -->
        <div class="mt-4">
            <p style="font-family: 'Arial', sans-serif; font-size: 16px; line-height: 1.5;">
                Our website respects your privacy and is committed to protecting your personal information. This Privacy Policy explains how we collect, use, and safeguard your data when you interact with our website.
            </p>
            <p style="font-family: 'Arial', sans-serif; font-size: 16px; line-height: 1.5;">
                We may collect your name, email address, and other contact information when you contact us. This information is used solely for the purpose of responding to your inquiries and providing you with the best possible service.
            </p>
            <p style="font-family: 'Arial', sans-serif; font-size: 16px; line-height: 1.5;">
                We do not share your personal information with third parties, and we take reasonable measures to protect your data.
            </p>
            <p style="font-family: 'Arial', sans-serif; font-size: 16px; line-height: 1.5;">
                By using our website, you consent to the terms of this Privacy Policy.
            </p>
            <p style="font-family: 'Arial', sans-serif; font-size: 16px; line-height: 1.5;">
                For more information, <a href="{% url 'contact' %}">contact us</a>.
            </p>
            
        </div>
    </div>
    
    
    <footer class="bg-light d-sm-block fixed-bottom">
        <div class="container d-flex justify-content-center align-items-center">
            <ul class="list-inline mb-0">
                <li class="list-inline-item">
                    <a class="nav-link" href="https://www.instagram.com/breddit_canada/">
                        <i class="fab fa-instagram"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="nav-link" href="https://www.facebook.com/profile.php?id=61553991453763">
                        <i class="fab fa-facebook"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="nav-link" href="https://twitter.com/BredditCanada">
                        <i class="fab fa-twitter"></i>
                    </a>
                </li>
            </ul>
        </div>
    </footer>
    <script>
        // Initialize Bootstrap components
        $(document).ready(function () {
            // Initialize Bootstrap Navbar
            $('.navbar-toggler').click(function () {
                $('#navbarNav').toggleClass('show');
            });
        });
    </script>
</body>
</html>
    